"""Build the Awesome list and a static, searchable GitHub Pages website."""
import html
import json
import shutil
from catalog import ROOT, TYPES, TOPICS, SCOPES, load, validate

def markdown(text):
    return html.escape(text).replace('[','&#91;').replace(']','&#93;').replace('*','&#42;').replace('_','&#95;').replace('`','&#96;').replace('\n',' ')

def build():
    resources = validate(load('resources.json'))
    out = ROOT / '_site'
    out.mkdir(exist_ok=True)
    for file in (ROOT/'site').iterdir():
        if file.is_file():
            shutil.copyfile(file, out/file.name)
    cards=[]
    lines=['<!-- Generated by scripts/build.py. Edit data/resources.json instead. -->','# Awesome Agent Security Learning','',
           'A curated learning library for securing, testing, evaluating, and governing AI agents.','',
           '[Browse the searchable website](https://joseruiz1571.github.io/awesome-agent-security-learning/) · [Start learning](docs/LEARNING_PATH.md) · [Maintainer walkthrough](docs/MAINTAINER_GUIDE.md) · [Contribute](CONTRIBUTING.md)','',
           'Automated discovery proposes additions every other week. A maintainer reviews and merges them. Inclusion is not an endorsement, and page inspection is not a course audit. Paid resources are welcome and labeled.','',
           'Agent-specific resources are separated from broader AI and foundational material. API, hosting, and model costs may apply to open-source labs.','',
           '## Contents','']
    for kind in TYPES:
        slug=kind.lower().replace(' & ','--').replace(' ','-')
        lines.append(f'- [{kind}](#{slug})')
    for kind in TYPES:
        lines += ['',f'## {kind}','']
        for r in sorted((r for r in resources if r['type']==kind),key=lambda r:r['title'].lower()):
            lines.append(f'- [{markdown(r["title"])}](<{r["url"]}>) — {markdown(r["description"])} **{r["cost"]}; {r["scope"]}.** {r["availability"]}.')
    lines += ['', '## Curation and discovery','',
        'The source of truth is [data/resources.json](data/resources.json). The website and this list are generated from it. Unresolved original suggestions remain in the [research inbox](data/research-inbox.json).', '',
        'Discovery combines Brave Search API (requires your repository secret), GitHub repository search, and selected RSS/Atom feeds. Search results are leads, not quality assessments. See [the review policy](CONTRIBUTING.md).', '',
        'Inspired by [Arcanum’s AI Security Resource Hub](https://github.com/Arcanum-Sec/ai-sec-resources). Original descriptions and implementation; no copied catalog or branding. Web discovery powered by [Brave Search API](https://brave.com/search/api/).', '',
        'Use labs and testing tools only in environments where you have authorization. Content and code in this repository are available under the MIT license; linked works retain their own licenses.','']
    (ROOT/'README.md').write_text('\n'.join(lines))
    for r in resources:
        esc=html.escape
        search=esc(' '.join([r['title'],r['description'],r['type'],r['scope'],*r['topics']]).lower(),quote=True)
        tags=''.join(f'<span>{esc(t)}</span>' for t in r['topics'])
        checked=f'Page inspected {r["checked_on"]}' if r['verification']=='Page inspected' else 'Metadata only · verify details'
        cards.append(f'''<article class="card" data-search="{search}" data-type="{esc(r['type'])}" data-topics="{esc('|'.join(r['topics']))}" data-scope="{esc(r['scope'])}" data-cost="{esc(r['cost'])}">
<div class="card-top"><span class="kind">{esc(r['type'])}</span><span class="scope">{esc(r['scope'])}</span></div>
<h3><a href="{esc(r['url'],quote=True)}" rel="noopener noreferrer">{esc(r['title'])} <span aria-hidden="true">↗</span></a></h3>
<p>{esc(r['description'])}</p><div class="tags">{tags}</div><div class="card-bottom"><span>{esc(r['cost'])}</span><span>{esc(r['availability'])}</span></div><small>{esc(checked)}</small></article>''')
    template=(ROOT/'site/index.html').read_text()
    for token,value in {'CARDS':'\n'.join(cards),'COUNT':str(len(resources)), 'TYPES':''.join(f'<option>{html.escape(t)}</option>' for t in TYPES), 'TOPICS':''.join(f'<option>{html.escape(t)}</option>' for t in TOPICS), 'SCOPES':''.join(f'<option>{html.escape(t)}</option>' for t in SCOPES)}.items():
        template=template.replace('{{'+token+'}}',value)
    (out/'index.html').write_text(template)
    (out/'resources.json').write_text(json.dumps(resources,ensure_ascii=False,indent=2)+'\n')
    (out/'.nojekyll').touch()
    print(f'Built {len(resources)} resource cards and README.md')

if __name__=='__main__':
    build()
